# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CSV creation script
      run: |
        python main.py

    - name: Upload files to the repo
      run: |
        git config --global user.email "sputhila@unomaha.edu"
        git config --global user.name "SaiLavanyaPuthila"
        git add .
        git commit -m "Updated CSV files"
        git push origin HEAD:master
